### ISSUE TITLE
Alterar tipo de dados da coluna 'imDocumento' da tabela 'sac.tbDocumentosAgentes' para varchar

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/salic-br#103]
- [ ] Alterar tipo de dados da coluna 'imDocumento' da tabela 'sac.tbDocumentosAgentes' para varchar

**Comment by heronbonfim** [comment]
Tipo de dado do atributo "imDocumento" da tabela sac."tbDocumentosAgentes" modificado para character varying(250).

**Comment by vinnyfs89** [comment]
Boa! Obrigado!
