### ISSUE TITLE
[Postgres] Erro de tamanho nos campos do tipo money

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-br#127]
Ao inserir valores com mais de 4 números o postgres não registra.

Tabelas encontradas:
PlanoDistribuicaoProduto
tbDetalhaPlanoDistribuicao
tbPlanilhaProposta
tbPlanilhaProjeto

**Comment by heronbonfim** [comment]
Campos alterados de money para numeric(12, 2)
