### ISSUE TITLE
Sprint Review - Sprint 2

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/salic-br#133]
- [x] Executar Sprint Review da Sprint 2

**Comment by vinnyfs89** [comment]
Sala de reuniões reservada para 14:30 até 15:30

:+1:

**Comment by isaiassm** [comment]
pontos positivos e negativos do projeto salic BR: Como primeiro projeto que estou participando não tenho pontos negativos a respeito do projeto, Ja conhecia a linguagem ultilizada no projeto, porém não da forma tão complexa como tenho visto, ainda estou pegando o jeito com os comandos git pois não tinha trabalhado com a ferramenta ainda, aprendendo muito com o jeito de trabalhar "pair programing" buscar informaçoes é sempre importante, e desta forma estou pegando muitas coisas. estou me familiarizando com o projeto e o codigo agora e pretendo nessa proxima sprint poder ajudar mais.

**Comment by vinnyfs89** [comment]
Atividade concluída pelo time.
