### ISSUE TITLE
Sprint Planning - Sprint 3

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/salic-br#134]
- [ ] Realizar planejamento de atividades para que sejam entregues na Sprint 3
- [ ] Verificar com time atividades que não foram listadas e devem entrar no Backlog

**Comment by vinnyfs89** [comment]
Atividade não mapeada no backlog:
- [ ] Definição de Perfis de acesso de Usuário x Orgão x Grupo para acesso a Admissibilidade

**Comment by nitaibezerra** [comment]
Sugiro/recomendo não registrar as reuniões/ritos do Scrum como issues

**Comment by vinnyfs89** [comment]
ok!
