### ISSUE TITLE
22 - Proposta Cultural - Plano de Distribuição - detalhamento por produto e local de realização

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/salic-br#30]
Tornar funcional a funcionalidade:

Cadastro de novo detalhamento por produto e local de realização
- [x] Editar Produto
- [x] Remover Produto

**Comment by clebersantos** [comment]
Para remover os itens da planilha orçamentária tem que refatorar o cadastramento de itens antes, este item será movido para uma nova issue.
