### ISSUE TITLE
25 - Proposta Cultural- Itens orçamentários

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/salic-br#33]
Tornar funcional a funcionalidade: Itens orçamentários
- [x] Solicitar inclusão de itens
	(http://localhost/proposta/mantertabelaitens/index/idPreProjeto/240082?idPreProjeto=240082)
- [ ] Permite pesquisar por itens cadastrados por produto e etapa
	Lista itens cadastrados (http://localhost/proposta/mantertabelaitens/exibirdados/idPreProjeto/240082)
- [x] Criar Novo Item - Solicitar associar Item a Produto/Etapa - Cadastrar associação entre produto, etapa e seleção de um item
- [x] Criar Novo Item - Solicitar associar Item a Incluir novo Item - Cadastrar associação entre produto, etapa e cria um item
	( OBS: na versão atual do SALICBR esse item não funciona e precisa ser corrigido, também )
- [ ] Quando remover um produto é atualmente acionada uma trigger para remover os itens orçamentários

**Comment by clebersantos** [comment]
@guiamado e @ShinNin-chan vcs estão tocando essa issue?

**Comment by guiamado** [comment]
Então @clebersantos , estamos esperando encontrar com o @vinnyfs89 para ver se ele acha interessante da gente tocar essa parte.

**Comment by vinnyfs89** [comment]
Me esperando? Podiam me chamar no telegram ou rocket.chat, não?

Essa atividade acredito ser complexa para vocês pegarem.

Sugiro que façam aquela atividade de varrer o cósigo-fonte utilizado e buscar trechos que podem ser jogados para Zend_Db.

Conseguiram concluir os testes no GerarPdf? Podemos testar?

**Comment by guiamado** [comment]
Ok, vamos varrer o código buscando os trechos para colocar em Zend_Db.

A parte do GerarPdf, ontem foi feito o merge para dev do repositorio do Lablivre, e está funcionando.
