### ISSUE TITLE
Migração da função "sac.fnChecarLiberacaoDaAdequacaoDoProjeto" para Postgres

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/salic-br#83]
- [x] Migração da função "sac.fnChecarLiberacaoDaAdequacaoDoProjeto" para Postgres

**Comment by heronbonfim** [comment]
Vinícius,

A função foi migrada. Favor verificar.

-- Function: sac."fnChecarLiberacaoDaAdequacaoDoProjeto"(integer)

-- DROP FUNCTION sac."fnChecarLiberacaoDaAdequacaoDoProjeto"(integer);

CREATE OR REPLACE FUNCTION sac."fnChecarLiberacaoDaAdequacaoDoProjeto"(p_p_idpronac integer) RETURNS integer AS
$BODY$

     DECLARE v_Liberar  INT;
             v_Situacao CHAR(3);
             v_Exists   INT;
     BEGIN
          v_Liberar := 0;

          SELECT "Situacao" INTO v_Situacao FROM sac."Projetos" WHERE "IdPRONAC" = p_p_idPronac;

          IF v_Situacao = 'E90' THEN
               v_Liberar := 1;
          ELSE
               SELECT COUNT(*) INTO v_Exists
               FROM   sac."tbAvaliarAdequacaoProjeto"
               WHERE  "idPronac"             = p_p_idPronac
                      AND "siEncaminhamento" = 16
                      AND "stAvaliacao"      = 2
                      AND "stEstado"         = '1';

               IF v_Exists > 0 THEN
                    v_Liberar := 1;
               END IF;

          END IF;

          RETURN(v_Liberar);
     END;

     $BODY$

     LANGUAGE plpgsql VOLATILE;

ALTER FUNCTION sac."fnChecarLiberacaoDaAdequacaoDoProjeto"(integer) OWNER TO postgres;

**Comment by vinnyfs89** [comment]
@heronbonfim Acabei de testar novamente, porém o erro permanece conforme imagem anexo.

![screenshot from 2017-10-24 16-43-58](https://user-images.githubusercontent.com/3949238/31961806-9c28e894-b8da-11e7-896b-c469e340848c.png)

**Comment by heronbonfim** [comment]
@vinnyfs89 Na linha 2 do rastreamento do erro há uma chamada da seguinte forma: "select sac.dbo...". Este dbo não vai funcionar... Não estou dizendo que este é o erro mas pode ser um problema.

**Comment by vinnyfs89** [comment]
Identifiquei que agora o erro é gerado porque a function espera um valor para ser informado e no postgres caso nenhum valor seja informado é lançada uma exception no para a aplicação.

**Comment by vinnyfs89** [comment]
Adicionei um tratamento para quando o valor não é informado e agora está funcional o uso dessa function.
