### ISSUE TITLE
Testes com nomes duplicados

### ISSUE THREAD

**Issue by navarrovmn** [culturagovbr/salic-br#87]
Existem classes de testes com nomes iguais que impedem o _script_ de testes de funcionar normalmente. Exemplos:
-   class MensagemControllerTest em _tests/application/modules/admissibilidade/RecursoCoordenadorControllerTest.php_ **e** _tests/application/modules/admissibilidade/MensagemControllerTest.php_
-  class RespostaControllerTest em _tests/application/modules/admissibilidade/TransfEmProjetoControllerTest.php_ **e** _tests/application/modules/admissibilidade/RespostaControllerTest.php_

**Comment by vinnyfs89** [comment]
Esses testes estão defasados, como comentei anteriormente com o time do Lappis, no momento não estão sendo utilizados os testes do PHPUnit.
