### ISSUE TITLE
Tabela 'TbDocumentosPreProjeto' Inexistente

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/salic-br#89]
Foi identificado que a tabela 'TbDocumentosPreProjeto' não existe ou não está acessível.

**Comment by vinnyfs89** [comment]
A ausência da tabela está ocasionando o seguinte erro:

![screenshot from 2017-11-24 16-37-25](https://user-images.githubusercontent.com/3949238/33221420-854bef4e-d136-11e7-8dcc-124782933433.png)

**Comment by yuricmarques** [comment]
Closes #89
