### ISSUE TITLE
Mapear banco minimo postgres

### ISSUE THREAD

**Issue by marcusvinicus** [culturagovbr/salic-br#95]
Fazer navegação detalhada para mapeamento do log do banco de dados

**Comment by vinnyfs89** [comment]
Senhores, conforme alinhamos moveremos essa atividade para a Sprint 2 que inicia dia 16/12/2017 que será quando o @clebersantos voltará para o projeto SalicBR.

**Comment by vinnyfs89** [comment]
O @clebersantos e eu nos reunimos hoje em conjunto com o @heronbonfim e mapeamos as tabelas utilizadas pelo SalicBR no fluxo da Admissibilidade utilizando um Trace Viewer para o SQL Server.

O @heronbonfim informou que conseguiu capturar todas as tabelas, functions, triggers e views utilizadas no processo de consulta, alteração, inclusão e remoção.

Agora o próximo passo é gerar um banco mínimo viável postgres para ajudar a compor a solução da stack docker da aplicação.
