### ISSUE TITLE
Corrigir falha na verificação para copiar o arquivo "exemplo-application.ini" para "application.ini"

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/salic-br#98]
Utilizando o repositório "docker-salic-br":

- [x] Corrigir validação utilizada para copiar o arquivo "exemplo-application.ini" para "application.ini".
- [x] Testar correção

Dica: ao clonar o repositório culturagovbr/docker-salic-br descomentar somente para teste as linhas que compartilham o diretório atual da aplicação para que seja clonado e testado no próprio diretório. 

OBS: Tomar cuidado para não fazer o push para o repositório com a pasta compartilhada da aplicação.

**Comment by vinnyfs89** [comment]
Favor, adicionar o Isaías a essa Issue.

**Comment by guiamado** [comment]
Favor verificar o Pull Request feito com a correção da falha.

**Comment by vinnyfs89** [comment]
Senhores Code Review realizado e pull request aceito. Parabéns!
